version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "8000"
  apartments:
    build: ./apartments
    ports:
      - "8080"
  bookings:
    build: ./bookings
    ports:
      - "8081"
  search:
    build: ./search
    ports:
      - "8082"
  rabbitMQ:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"